# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.fabulous.com/status_registered_03076.com.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/record/parser/whois.fabulous.com.rb'

describe Whois::Record::Parser::WhoisFabulousCom, "status_registered_03076.com.expected" do

  before(:each) do
    file = fixture("responses", "whois.fabulous.com/status_registered_03076.com.txt")
    part = Whois::Record::Part.new(:body => File.read(file))
    @parser = klass.new(part)
  end

  describe "#status" do
    it do
      @parser.status.should == :registered
    end
  end
  describe "#available?" do
    it do
      @parser.available?.should == false
    end
  end
  describe "#registered?" do
    it do
      @parser.registered?.should == true
    end
  end
  describe "#created_on" do
    it do
      @parser.created_on.should be_a(Time)
      @parser.created_on.should == Time.parse("2008-10-17 19:39:15 UTC")
    end
  end
  describe "#updated_on" do
    it do
      @parser.updated_on.should be_a(Time)
      @parser.updated_on.should == Time.parse("2011-09-28 14:14:49 UTC")
    end
  end
  describe "#expires_on" do
    it do
      @parser.expires_on.should be_a(Time)
      @parser.expires_on.should == Time.parse("2012-10-17 UTC")
    end
  end
  describe "#registrar" do
    it do
      @parser.registrar.should be_a(Whois::Record::Registrar)
      @parser.registrar.id.should           == nil
      @parser.registrar.name.should         == "Fabulous.com"
      @parser.registrar.organization.should == "Fabulous.com Pty Ltd"
      @parser.registrar.url.should          == "http://www.fabulous.com"
    end
  end
  describe "#registrant_contacts" do
    it do
      @parser.registrant_contacts.should be_a(Array)
      @parser.registrant_contacts.should have(1).items
      @parser.registrant_contacts[0].should be_a(Whois::Record::Contact)
      @parser.registrant_contacts[0].type.should         == Whois::Record::Contact::TYPE_REGISTRANT
      @parser.registrant_contacts[0].id.should           == "59314360577865"
      @parser.registrant_contacts[0].name.should         == "Domain Hostmaster"
      @parser.registrant_contacts[0].organization.should == "Whois Privacy Services Pty Ltd"
      @parser.registrant_contacts[0].address.should      == "PO Box 923"
      @parser.registrant_contacts[0].city.should         == "Fortitude Valley"
      @parser.registrant_contacts[0].state.should        == "QLD"
      @parser.registrant_contacts[0].zip.should          == "4006"
      @parser.registrant_contacts[0].country_code.should == "AU"
      @parser.registrant_contacts[0].phone.should        == nil
      @parser.registrant_contacts[0].fax.should          == nil
      @parser.registrant_contacts[0].email.should        == "59314360577865-ba6f51@whoisprivacyservices.com.au"
    end
  end
  describe "#admin_contacts" do
    it do
      @parser.admin_contacts.should be_a(Array)
      @parser.admin_contacts.should have(0).items
    end
  end
  describe "#technical_contacts" do
    it do
      @parser.technical_contacts.should be_a(Array)
      @parser.technical_contacts.should have(0).items
    end
  end
  describe "#nameservers" do
    it do
      @parser.nameservers.should be_a(Array)
      @parser.nameservers.should have(2).items
      @parser.nameservers[0].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[0].name.should == "ns1.fabulous.com"
      @parser.nameservers[0].ipv4.should == nil
      @parser.nameservers[1].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[1].name.should == "ns2.fabulous.com"
      @parser.nameservers[1].ipv4.should == nil
    end
  end
end
