# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.moniker.com/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/record/parser/whois.moniker.com.rb'

describe Whois::Record::Parser::WhoisMonikerCom, "status_registered.expected" do

  before(:each) do
    file = fixture("responses", "whois.moniker.com/status_registered.txt")
    part = Whois::Record::Part.new(:body => File.read(file))
    @parser = klass.new(part)
  end

  describe "#status" do
    it do
      @parser.status.should == :registered
    end
  end
  describe "#available?" do
    it do
      @parser.available?.should == false
    end
  end
  describe "#registered?" do
    it do
      @parser.registered?.should == true
    end
  end
  describe "#created_on" do
    it do
      @parser.created_on.should be_a(Time)
      @parser.created_on.should == Time.parse("2004-03-18 14:05:56 UTC")
    end
  end
  describe "#updated_on" do
    it do
      @parser.updated_on.should be_a(Time)
      @parser.updated_on.should == Time.parse("2012-06-07 16:37:30 UTC")
    end
  end
  describe "#expires_on" do
    it do
      @parser.expires_on.should be_a(Time)
      @parser.expires_on.should == Time.parse("2017-03-04 00:00:00 UTC")
    end
  end
  describe "#registrar" do
    it do
      @parser.registrar.should be_a(Whois::Record::Registrar)
      @parser.registrar.id.should           == nil
      @parser.registrar.name.should         == "Moniker"
      @parser.registrar.organization.should == "Moniker Online Services LLC"
      @parser.registrar.url.should          == "http://moniker.com"
    end
  end
  describe "#registrant_contacts" do
    it do
      @parser.registrant_contacts.should be_a(Array)
      @parser.registrant_contacts.should have(1).items
      @parser.registrant_contacts[0].should be_a(Whois::Record::Contact)
      @parser.registrant_contacts[0].type.should         == Whois::Record::Contact::TYPE_REGISTRANT
      @parser.registrant_contacts[0].id.should           == "3793977"
      @parser.registrant_contacts[0].name.should         == "Domain Manager"
      @parser.registrant_contacts[0].organization.should == "Moniker Online Services, LLC"
      @parser.registrant_contacts[0].address.should      == "20 SW 27th Ave.\nSuite 201"
      @parser.registrant_contacts[0].city.should         == "Pompano Beach"
      @parser.registrant_contacts[0].zip.should          == "33069"
      @parser.registrant_contacts[0].state.should        == "FL"
      @parser.registrant_contacts[0].country_code.should == "US"
      @parser.registrant_contacts[0].phone.should        == nil
      @parser.registrant_contacts[0].fax.should          == nil
      @parser.registrant_contacts[0].email.should        == "domains@moniker.com"
    end
  end
  describe "#admin_contacts" do
    it do
      @parser.admin_contacts.should be_a(Array)
      @parser.admin_contacts.should have(1).items
      @parser.admin_contacts[0].should be_a(Whois::Record::Contact)
      @parser.admin_contacts[0].type.should         == Whois::Record::Contact::TYPE_ADMIN
      @parser.admin_contacts[0].id.should           == "3793977"
      @parser.admin_contacts[0].name.should         == "Domain Manager"
      @parser.admin_contacts[0].organization.should == "Moniker Online Services, LLC"
      @parser.admin_contacts[0].address.should      == "20 SW 27th Ave.\nSuite 201"
      @parser.admin_contacts[0].city.should         == "Pompano Beach"
      @parser.admin_contacts[0].zip.should          == "33069"
      @parser.admin_contacts[0].state.should        == "FL"
      @parser.admin_contacts[0].country_code.should == "US"
      @parser.admin_contacts[0].phone.should        == "+1.9549848445"
      @parser.admin_contacts[0].fax.should          == "+1.9549699155"
      @parser.admin_contacts[0].email.should        == "domains@moniker.com"
    end
  end
  describe "#technical_contacts" do
    it do
      @parser.technical_contacts.should be_a(Array)
      @parser.technical_contacts.should have(1).items
      @parser.technical_contacts[0].should be_a(Whois::Record::Contact)
      @parser.technical_contacts[0].type.should         == Whois::Record::Contact::TYPE_TECHNICAL
      @parser.technical_contacts[0].id.should           == "3793977"
      @parser.technical_contacts[0].name.should         == "Domain Manager"
      @parser.technical_contacts[0].organization.should == "Moniker Online Services, LLC"
      @parser.technical_contacts[0].address.should      == "20 SW 27th Ave.\nSuite 201"
      @parser.technical_contacts[0].city.should         == "Pompano Beach"
      @parser.technical_contacts[0].zip.should          == "33069"
      @parser.technical_contacts[0].state.should        == "FL"
      @parser.technical_contacts[0].country_code.should == "US"
      @parser.technical_contacts[0].phone.should        == "+1.9549848445"
      @parser.technical_contacts[0].fax.should          == "+1.9549699155"
      @parser.technical_contacts[0].email.should        == "domains@moniker.com"
    end
  end
  describe "#nameservers" do
    it do
      @parser.nameservers.should be_a(Array)
      @parser.nameservers.should have(4).items
      @parser.nameservers[0].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[0].name.should == "ns1.moniker.com"
      @parser.nameservers[0].ipv4.should == "207.189.109.115"
      @parser.nameservers[1].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[1].name.should == "ns2.moniker.com"
      @parser.nameservers[1].ipv4.should == "63.156.206.115"
      @parser.nameservers[2].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[2].name.should == "ns3.moniker.com"
      @parser.nameservers[2].ipv4.should == "50.57.11.89"
      @parser.nameservers[3].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[3].name.should == "ns4.moniker.com"
      @parser.nameservers[3].ipv4.should == "50.57.11.88"
    end
  end
end
