# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.tucows.com/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/record/parser/whois.tucows.com.rb'

describe Whois::Record::Parser::WhoisTucowsCom, "status_registered.expected" do

  before(:each) do
    file = fixture("responses", "whois.tucows.com/status_registered.txt")
    part = Whois::Record::Part.new(:body => File.read(file))
    @parser = klass.new(part)
  end

  describe "#status" do
    it do
      @parser.status.should == :registered
    end
  end
  describe "#available?" do
    it do
      @parser.available?.should == false
    end
  end
  describe "#registered?" do
    it do
      @parser.registered?.should == true
    end
  end
  describe "#created_on" do
    it do
      @parser.created_on.should be_a(Time)
      @parser.created_on.should == Time.parse("1995-09-07")
    end
  end
  describe "#updated_on" do
    it do
      @parser.updated_on.should be_a(Time)
      @parser.updated_on.should == Time.parse("2011-08-07")
    end
  end
  describe "#expires_on" do
    it do
      @parser.expires_on.should be_a(Time)
      @parser.expires_on.should == Time.parse("2012-09-06")
    end
  end
  describe "#registrar" do
    it do
      @parser.registrar.should be_a(Whois::Record::Registrar)
      @parser.registrar.id.should           == nil
      @parser.registrar.name.should         == "Tucows"
      @parser.registrar.organization.should == "Tucows, Inc."
      @parser.registrar.url.should          == "http://tucowsdomains.com"
    end
  end
  describe "#registrant_contacts" do
    it do
      @parser.registrant_contacts.should be_a(Array)
      @parser.registrant_contacts.should have(1).items
      @parser.registrant_contacts[0].should be_a(Whois::Record::Contact)
      @parser.registrant_contacts[0].type.should         == Whois::Record::Contact::TYPE_REGISTRANT
      @parser.registrant_contacts[0].id.should           == nil
      @parser.registrant_contacts[0].name.should         == nil
      @parser.registrant_contacts[0].organization.should == "Tucows.com Co"
      @parser.registrant_contacts[0].address.should      == "96 Mowat Avenue"
      @parser.registrant_contacts[0].city.should         == "Toronto"
      @parser.registrant_contacts[0].zip.should          == "M6K3M1"
      @parser.registrant_contacts[0].state.should        == "Ontario"
      @parser.registrant_contacts[0].country_code.should == "CA"
      @parser.registrant_contacts[0].phone.should        == nil
      @parser.registrant_contacts[0].fax.should          == nil
      @parser.registrant_contacts[0].email.should        == nil
    end
  end
  describe "#admin_contacts" do
    it do
      @parser.admin_contacts.should be_a(Array)
      @parser.admin_contacts.should have(1).items
      @parser.admin_contacts[0].should be_a(Whois::Record::Contact)
      @parser.admin_contacts[0].type.should         == Whois::Record::Contact::TYPE_ADMIN
      @parser.admin_contacts[0].id.should           == nil
      @parser.admin_contacts[0].name.should         == "Administrator, DNS"
      @parser.admin_contacts[0].organization.should == nil
      @parser.admin_contacts[0].address.should      == "96 Mowat Avenue"
      @parser.admin_contacts[0].city.should         == "Toronto"
      @parser.admin_contacts[0].zip.should          == "M6K3M1"
      @parser.admin_contacts[0].state.should        == "Ontario"
      @parser.admin_contacts[0].country_code.should == "CA"
      @parser.admin_contacts[0].phone.should        == "+1.4165350123x0000"
      @parser.admin_contacts[0].fax.should          == nil
      @parser.admin_contacts[0].email.should        == "dnsadmin@tucows.com"
    end
  end
  describe "#technical_contacts" do
    it do
      @parser.technical_contacts.should be_a(Array)
      @parser.technical_contacts.should have(1).items
      @parser.technical_contacts[0].should be_a(Whois::Record::Contact)
      @parser.technical_contacts[0].type.should         == Whois::Record::Contact::TYPE_TECHNICAL
      @parser.technical_contacts[0].id.should           == nil
      @parser.technical_contacts[0].name.should         == "Administrator, DNS"
      @parser.technical_contacts[0].organization.should == nil
      @parser.technical_contacts[0].address.should      == "96 Mowat Avenue"
      @parser.technical_contacts[0].city.should         == "Toronto"
      @parser.technical_contacts[0].zip.should          == "M6K3M1"
      @parser.technical_contacts[0].state.should        == "Ontario"
      @parser.technical_contacts[0].country_code.should == "CA"
      @parser.technical_contacts[0].phone.should        == "+1.4165350123x0000"
      @parser.technical_contacts[0].fax.should          == nil
      @parser.technical_contacts[0].email.should        == "dnsadmin@tucows.com"
    end
  end
  describe "#nameservers" do
    it do
      @parser.nameservers.should be_a(Array)
      @parser.nameservers.should have(3).items
      @parser.nameservers[0].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[0].name.should == "ns3.tucows.com"
      @parser.nameservers[0].ipv4.should == "64.99.96.32"
      @parser.nameservers[1].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[1].name.should == "ns1.tucows.com"
      @parser.nameservers[1].ipv4.should == "216.40.47.20"
      @parser.nameservers[2].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[2].name.should == "ns2.tucows.com"
      @parser.nameservers[2].ipv4.should == "64.98.148.15"
    end
  end
end
