# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.resellerclub.com/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/record/parser/whois.resellerclub.com.rb'

describe Whois::Record::Parser::WhoisResellerclubCom, "status_registered.expected" do

  before(:each) do
    file = fixture("responses", "whois.resellerclub.com/status_registered.txt")
    part = Whois::Record::Part.new(:body => File.read(file))
    @parser = klass.new(part)
  end

  describe "#status" do
    it do
      @parser.status.should == :registered
    end
  end
  describe "#available?" do
    it do
      @parser.available?.should == false
    end
  end
  describe "#registered?" do
    it do
      @parser.registered?.should == true
    end
  end
  describe "#updated_on" do
    it do
      @parser.updated_on.should == nil
    end
  end
  describe "#created_on" do
    it do
      @parser.created_on.should be_a(Time)
      @parser.created_on.should == Time.parse("2003-10-20")
    end
  end
  describe "#expires_on" do
    it do
      @parser.expires_on.should be_a(Time)
      @parser.expires_on.should == Time.parse("2018-10-20")
    end
  end
  describe "#registrar" do
    it do
      @parser.registrar.should be_a(Whois::Record::Registrar)
      @parser.registrar.id.should           == nil
      @parser.registrar.name.should         == "ResellerClub.com"
      @parser.registrar.organization.should == "Directi Internet Solutions Pvt. Ltd."
      @parser.registrar.url.should          == "http://resellerclub.com"
    end
  end
  describe "#registrant_contacts" do
    it do
      @parser.registrant_contacts.should be_a(Array)
      @parser.registrant_contacts.should have(1).items
      @parser.registrant_contacts[0].should be_a(Whois::Record::Contact)
      @parser.registrant_contacts[0].type.should         == Whois::Record::Contact::TYPE_REGISTRANT
      @parser.registrant_contacts[0].id.should           == nil
      @parser.registrant_contacts[0].name.should         == "Domain Manager"
      @parser.registrant_contacts[0].organization.should == "ResellerClub.com"
      @parser.registrant_contacts[0].address.should      == "15500 SW Jay St. #48732"
      @parser.registrant_contacts[0].city.should         == "Beaverton"
      @parser.registrant_contacts[0].state.should        == "Oregon"
      @parser.registrant_contacts[0].zip.should          == "97006"
      @parser.registrant_contacts[0].country_code.should == "US"
      @parser.registrant_contacts[0].phone.should        == "+1.2013775952"
      @parser.registrant_contacts[0].fax.should          == nil
      @parser.registrant_contacts[0].email.should        == "domain.manager@resellerclub.com"
    end
  end
  describe "#admin_contacts" do
    it do
      @parser.admin_contacts.should be_a(Array)
      @parser.admin_contacts.should have(1).items
      @parser.admin_contacts[0].should be_a(Whois::Record::Contact)
      @parser.admin_contacts[0].type.should         == Whois::Record::Contact::TYPE_ADMIN
      @parser.admin_contacts[0].id.should           == nil
      @parser.admin_contacts[0].name.should         == "Domain Manager"
      @parser.admin_contacts[0].organization.should == "ResellerClub.com"
      @parser.admin_contacts[0].address.should      == "15500 SW Jay St. #48732"
      @parser.admin_contacts[0].city.should         == "Beaverton"
      @parser.admin_contacts[0].state.should        == "Oregon"
      @parser.admin_contacts[0].zip.should          == "97006"
      @parser.admin_contacts[0].country_code.should == "US"
      @parser.admin_contacts[0].phone.should        == "+1.2013775952"
      @parser.admin_contacts[0].fax.should          == nil
      @parser.admin_contacts[0].email.should        == "domain.manager@resellerclub.com"
    end
  end
  describe "#technical_contacts" do
    it do
      @parser.technical_contacts.should be_a(Array)
      @parser.technical_contacts.should have(1).items
      @parser.technical_contacts[0].should be_a(Whois::Record::Contact)
      @parser.technical_contacts[0].type.should         == Whois::Record::Contact::TYPE_TECHNICAL
      @parser.technical_contacts[0].id.should           == nil
      @parser.technical_contacts[0].name.should         == "Domain Manager"
      @parser.technical_contacts[0].organization.should == "ResellerClub.com"
      @parser.technical_contacts[0].address.should      == "15500 SW Jay St. #48732"
      @parser.technical_contacts[0].city.should         == "Beaverton"
      @parser.technical_contacts[0].state.should        == "Oregon"
      @parser.technical_contacts[0].zip.should          == "97006"
      @parser.technical_contacts[0].country_code.should == "US"
      @parser.technical_contacts[0].phone.should        == "+1.2013775952"
      @parser.technical_contacts[0].fax.should          == nil
      @parser.technical_contacts[0].email.should        == "domain.manager@resellerclub.com"
    end
  end
  describe "#nameservers" do
    it do
      @parser.nameservers.should be_a(Array)
      @parser.nameservers.should have(8).items
      @parser.nameservers[0].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[0].name.should == "asia1.akam.net"
      @parser.nameservers[0].ipv4.should == nil
      @parser.nameservers[1].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[1].name.should == "eur2.akam.net"
      @parser.nameservers[1].ipv4.should == nil
      @parser.nameservers[2].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[2].name.should == "eur4.akam.net"
      @parser.nameservers[2].ipv4.should == nil
      @parser.nameservers[3].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[3].name.should == "eur6.akam.net"
      @parser.nameservers[3].ipv4.should == nil
      @parser.nameservers[4].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[4].name.should == "ns1-106.akam.net"
      @parser.nameservers[4].ipv4.should == nil
      @parser.nameservers[5].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[5].name.should == "ns1-109.akam.net"
      @parser.nameservers[5].ipv4.should == nil
      @parser.nameservers[6].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[6].name.should == "usc4.akam.net"
      @parser.nameservers[6].ipv4.should == nil
      @parser.nameservers[7].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[7].name.should == "usc5.akam.net"
      @parser.nameservers[7].ipv4.should == nil
    end
  end
end
