# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.fastdomain.com/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/record/parser/whois.fastdomain.com.rb'

describe Whois::Record::Parser::WhoisFastdomainCom, "status_registered.expected" do

  before(:each) do
    file = fixture("responses", "whois.fastdomain.com/status_registered.txt")
    part = Whois::Record::Part.new(:body => File.read(file))
    @parser = klass.new(part)
  end

  describe "#status" do
    it do
      @parser.status.should == :registered
    end
  end
  describe "#available?" do
    it do
      @parser.available?.should == false
    end
  end
  describe "#registered?" do
    it do
      @parser.registered?.should == true
    end
  end
  describe "#created_on" do
    it do
      @parser.created_on.should be_a(Time)
      @parser.created_on.should == Time.parse("2002-11-07 05:49:33 GMT")
    end
  end
  describe "#updated_on" do
    it do
      @parser.updated_on.should be_a(Time)
      @parser.updated_on.should == Time.parse("2012-04-19 17:40:46 GMT")
    end
  end
  describe "#expires_on" do
    it do
      @parser.expires_on.should be_a(Time)
      @parser.expires_on.should == Time.parse("2017-11-07 05:49:33 GMT")
    end
  end
  describe "#registrar" do
    it do
      @parser.registrar.should be_a(Whois::Record::Registrar)
      @parser.registrar.id.should           == nil
      @parser.registrar.name.should         == "FastDomain"
      @parser.registrar.organization.should == "FastDomain Inc."
      @parser.registrar.url.should          == "http://www.fastdomain.com"
    end
  end
  describe "#registrant_contacts" do
    it do
      @parser.registrant_contacts.should be_a(Array)
      @parser.registrant_contacts.should have(1).items
      @parser.registrant_contacts[0].should be_a(Whois::Record::Contact)
      @parser.registrant_contacts[0].type.should         == Whois::Record::Contact::TYPE_REGISTRANT
      @parser.registrant_contacts[0].id.should           == "FAST-18447012"
      @parser.registrant_contacts[0].name.should         == "Domain Privacy Service"
      @parser.registrant_contacts[0].organization.should == nil
      @parser.registrant_contacts[0].address.should      == "1958 South 950 East"
      @parser.registrant_contacts[0].city.should         == "Provo"
      @parser.registrant_contacts[0].state.should        == "Utah"
      @parser.registrant_contacts[0].zip.should          == "-"
      @parser.registrant_contacts[0].country.should      == "United States"
      @parser.registrant_contacts[0].phone.should        == "+1.8014948462"
      @parser.registrant_contacts[0].fax.should          == nil
      @parser.registrant_contacts[0].email.should        == "whois@fastdomain.com"
    end
  end
  describe "#admin_contacts" do
    it do
      @parser.admin_contacts.should be_a(Array)
      @parser.admin_contacts.should have(1).items
      @parser.admin_contacts[0].should be_a(Whois::Record::Contact)
      @parser.admin_contacts[0].type.should         == Whois::Record::Contact::TYPE_ADMIN
      @parser.admin_contacts[0].id.should           == "FAST-18447012"
      @parser.admin_contacts[0].name.should         == "Domain Privacy Service"
      @parser.admin_contacts[0].organization.should == nil
      @parser.admin_contacts[0].address.should      == "1958 South 950 East"
      @parser.admin_contacts[0].city.should         == "Provo"
      @parser.admin_contacts[0].state.should        == "Utah"
      @parser.admin_contacts[0].zip.should          == "-"
      @parser.admin_contacts[0].country.should      == "United States"
      @parser.admin_contacts[0].phone.should        == "+1.8014948462"
      @parser.admin_contacts[0].fax.should          == nil
      @parser.admin_contacts[0].email.should        == "whois@fastdomain.com"
    end
  end
  describe "#technical_contacts" do
    it do
      @parser.technical_contacts.should be_a(Array)
      @parser.technical_contacts.should have(1).items
      @parser.technical_contacts[0].should be_a(Whois::Record::Contact)
      @parser.technical_contacts[0].type.should         == Whois::Record::Contact::TYPE_TECHNICAL
      @parser.technical_contacts[0].id.should           == "FAST-18447012"
      @parser.technical_contacts[0].name.should         == "Domain Privacy Service"
      @parser.technical_contacts[0].organization.should == nil
      @parser.technical_contacts[0].address.should      == "1958 South 950 East"
      @parser.technical_contacts[0].city.should         == "Provo"
      @parser.technical_contacts[0].state.should        == "Utah"
      @parser.technical_contacts[0].zip.should          == "-"
      @parser.technical_contacts[0].country.should      == "United States"
      @parser.technical_contacts[0].phone.should        == "+1.8014948462"
      @parser.technical_contacts[0].fax.should          == nil
      @parser.technical_contacts[0].email.should        == "whois@fastdomain.com"
    end
  end
  describe "#nameservers" do
    it do
      @parser.nameservers.should be_a(Array)
      @parser.nameservers.should have(2).items
      @parser.nameservers[0].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[0].name.should == "ns1.fastdomain.com"
      @parser.nameservers[0].ipv4.should == nil
      @parser.nameservers[1].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[1].name.should == "ns2.fastdomain.com"
      @parser.nameservers[1].ipv4.should == nil
    end
  end
end
