# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.wildwestdomains.com/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/record/parser/whois.wildwestdomains.com.rb'

describe Whois::Record::Parser::WhoisWildwestdomainsCom, "status_registered.expected" do

  before(:each) do
    file = fixture("responses", "whois.wildwestdomains.com/status_registered.txt")
    part = Whois::Record::Part.new(:body => File.read(file))
    @parser = klass.new(part)
  end

  describe "#status" do
    it do
      @parser.status.should == :registered
    end
  end
  describe "#available?" do
    it do
      @parser.available?.should == false
    end
  end
  describe "#registered?" do
    it do
      @parser.registered?.should == true
    end
  end
  describe "#created_on" do
    it do
      @parser.created_on.should be_a(Time)
      @parser.created_on.should == Time.parse("2000-08-22")
    end
  end
  describe "#updated_on" do
    it do
      @parser.updated_on.should be_a(Time)
      @parser.updated_on.should == Time.parse("2011-11-01")
    end
  end
  describe "#expires_on" do
    it do
      @parser.expires_on.should be_a(Time)
      @parser.expires_on.should == Time.parse("2021-11-01")
    end
  end
  describe "#registrar" do
    it do
      @parser.registrar.should be_a(Whois::Record::Registrar)
      @parser.registrar.id.should           == nil
      @parser.registrar.name.should         == "Wild West Domains"
      @parser.registrar.organization.should == "Wild West Domains"
      @parser.registrar.url.should          == "http://wwdomains.com"
    end
  end
  describe "#registrant_contacts" do
    it do
      @parser.registrant_contacts.should be_a(Array)
      @parser.registrant_contacts.should have(1).items
      @parser.registrant_contacts[0].should be_a(Whois::Record::Contact)
      @parser.registrant_contacts[0].type.should         == Whois::Record::Contact::TYPE_REGISTRANT
      @parser.registrant_contacts[0].id.should           == nil
      @parser.registrant_contacts[0].name.should         == nil
      @parser.registrant_contacts[0].organization.should == "Wild West Domains"
      @parser.registrant_contacts[0].address.should      == "14455 N Hayden Rd Suite 219"
      @parser.registrant_contacts[0].city.should         == "Scottsdale"
      @parser.registrant_contacts[0].state.should        == "Arizona"
      @parser.registrant_contacts[0].zip.should          == "85260"
      @parser.registrant_contacts[0].country.should      == "United States"
      @parser.registrant_contacts[0].phone.should        == nil
      @parser.registrant_contacts[0].fax.should          == nil
      @parser.registrant_contacts[0].email.should        == nil
    end
  end
  describe "#admin_contacts" do
    it do
      @parser.admin_contacts.should be_a(Array)
      @parser.admin_contacts.should have(1).items
      @parser.admin_contacts[0].should be_a(Whois::Record::Contact)
      @parser.admin_contacts[0].type.should         == Whois::Record::Contact::TYPE_ADMIN
      @parser.admin_contacts[0].id.should           == nil
      @parser.admin_contacts[0].name.should         == "Wild West Domains, Wild West Domains"
      @parser.admin_contacts[0].organization.should == "Wild West Domains"
      @parser.admin_contacts[0].address.should      == "14455 N Hayden Rd Suite 219"
      @parser.admin_contacts[0].city.should         == "Scottsdale"
      @parser.admin_contacts[0].state.should        == "Arizona"
      @parser.admin_contacts[0].zip.should          == "85260"
      @parser.admin_contacts[0].country.should      == "United States"
      @parser.admin_contacts[0].phone.should        == "+1.4805058800"
      @parser.admin_contacts[0].fax.should          == "+1.4805058844"
      @parser.admin_contacts[0].email.should        == "dns@wildwestdomains.com"
    end
  end
  describe "#technical_contacts" do
    it do
      @parser.technical_contacts.should be_a(Array)
      @parser.technical_contacts.should have(1).items
      @parser.technical_contacts[0].should be_a(Whois::Record::Contact)
      @parser.technical_contacts[0].type.should         == Whois::Record::Contact::TYPE_TECHNICAL
      @parser.technical_contacts[0].id.should           == nil
      @parser.technical_contacts[0].name.should         == "Wild West Domains, Wild West Domains"
      @parser.technical_contacts[0].organization.should == "Wild West Domains"
      @parser.technical_contacts[0].address.should      == "14455 N Hayden Rd Suite 219"
      @parser.technical_contacts[0].city.should         == "Scottsdale"
      @parser.technical_contacts[0].state.should        == "Arizona"
      @parser.technical_contacts[0].zip.should          == "85260"
      @parser.technical_contacts[0].country.should      == "United States"
      @parser.technical_contacts[0].phone.should        == "+1.4805058800"
      @parser.technical_contacts[0].fax.should          == "+1.4805058844"
      @parser.technical_contacts[0].email.should        == "dns@wildwestdomains.com"
    end
  end
  describe "#nameservers" do
    it do
      @parser.nameservers.should be_a(Array)
      @parser.nameservers.should have(3).items
      @parser.nameservers[0].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[0].name.should == "cns1.secureserver.net"
      @parser.nameservers[0].ipv4.should == nil
      @parser.nameservers[1].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[1].name.should == "cns2.secureserver.net"
      @parser.nameservers[1].ipv4.should == nil
      @parser.nameservers[2].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[2].name.should == "cns3.secureserver.net"
      @parser.nameservers[2].ipv4.should == nil
    end
  end
end
